algoritmo "ContagemAutomatica"
// Disciplina   : [Linguagem e Lógica de Programação] 
// Professor   : Antonio Carlos Nicolodi 
var

   Comeco, fim, contador : Inteiro

inicio

   Escreva ("Qual o inicio da contagem? ")
   Leia (Comeco)
   Escreva ("Qual o Fim da contagem? ")
   Leia (fim)
   
   
   contador <- 0
   Enquanto (contador <= fim) faca
       contador <- contador + 1
       Escreval (contador)
       

   FimEnquanto
   Escreval ("Terminei de contar" )

fimalgoritmo