algoritmo "PartidaDeFutebol"
var
   Bangu, Madureira, Gol : REAL

inicio

   Escreva ("Quantos gols Bangu fez? ")
   Leia (Bangu)
   Escreva ("Quantos Gol Madureira fez? ")
   Leia (Madureira)
   Gol <- Bangu - Madureira
   Escreval ("Diferença:", Gol (Abs))
   
   Escolha Gol
   Caso = 0
      Escreval ("Empate")
   Caso 1, 2, 3
      Escreval ("Jogo normal")
   OutroCaso
      Escreval ("Goleada")

   FimEscolha



fimalgoritmo